# Generated by Django 4.1.1 on 2022-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0004_repositoriogithub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoriogithub',
            name='language',
            field=models.CharField(max_length=10, null=True, verbose_name='Lenguaje'),
        ),
    ]
