# Generated by Django 4.1.1 on 2022-09-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0006_alter_repositoriogithub_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoriogithub',
            name='open_issues',
            field=models.IntegerField(null=True),
        ),
    ]
