# Generated by Django 4.1.1 on 2022-09-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0007_alter_repositoriogithub_open_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepositorioGithub',
        ),
    ]
