# Generated by Django 4.1.1 on 2022-09-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositorioGithub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('created', models.DateTimeField()),
                ('language', models.CharField(max_length=10, null=True, verbose_name='Lenguaje')),
                ('username', models.CharField(max_length=100, verbose_name='Usuario')),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('subscribers', models.IntegerField(null=True)),
                ('open_issues', models.IntegerField(null=True)),
                ('days_alive', models.IntegerField()),
            ],
            options={
                'verbose_name': 'RepositorioGithub',
                'verbose_name_plural': 'RepositorioGithubs',
            },
        ),
    ]
