# Generated by Django 4.1.1 on 2022-09-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Direción'),
        ),
    ]
